# Specify the base image
FROM python:3.10-alpine

# Create a directory for the app
RUN mkdir /app

# Set the working directory
WORKDIR /app

# Copy the app files into the directory
COPY . /app

# Install the necessary dependencies from the requirements.txt file
RUN pip install -r requirements.txt

# EXPOSE 5000
EXPOSE 5000

# Specify the command to run the app
ENTRYPOINT [ "python" ]

CMD ["ReceiveMsgServer.py" ]