# Specify the base image
FROM python:3.8-slim

# Create a directory for the app
RUN mkdir /app

# Set the working directory
WORKDIR /app

# Copy the app files into the directory
COPY . /app
COPY ../requirements.txt /app

# Install the necessary dependencies from the requirements.txt file
RUN pip install -r requirements.txt

# Specify the command to run the app
CMD ["gunicorn", "-w", "4", "app:app"]