# Specify the base image
FROM python:3.8-alpine

# Create a directory for the app
RUN mkdir /app

# Set the working directory
WORKDIR /app

# Copy the app files into the directory
COPY . /app
COPY ../requirements.txt /app

# Install the necessary dependencies from the requirements.txt file
RUN pip install -r requirements.txt

# Specify the command to run the app
ENTRYPOINT [ "python" ]

CMD ["RecieveMsgServer.py" ]